BEGIN;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(32) NOT NULL UNIQUE,
	password_hash VARCHAR(256) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE messages (
	id SERIAL NOT NULL PRIMARY KEY,
	sender VARCHAR(32) NOT NULL REFERENCES users(name),
	dest_id INTEGER REFERENCES users(id),
	message_text TEXT
);
COMMIT;


